[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[project]
name = "mismo"
description = ''
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.9" # require >3.9 so that we can use ibis>=6
license = { text = "LGPL-3.0-or-later" }
keywords = []
authors = [{ name = "Nick Crews", email = "nicholas.b.crews@gmail.com" }]
classifiers = [
  "Development Status :: 3 - Alpha",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: Implementation :: CPython",
  "Programming Language :: Python :: Implementation :: PyPy",
]
dependencies = [
  "altair>=5.0.0",
  "anywidget",
  # "ibis-framework[duckdb]>=7.2.0",
  # "ibis-framework[duckdb]>=9.0.0.dev34",
  "ibis-framework[duckdb] @ git+https://github.com/ibis-project/ibis.git@7ab4fda354986715ec55eec2d20edbcc4c3db65b",
  "ipywidgets",
  "scikit-learn",
  "typing-extensions ; python_version < \"3.11\"", # needed for Self
]

[project.urls]
Documentation = "https://nickcrews.github.io/mismo"
Issues = "https://github.com/NickCrews/mismo/issues"
Source = "https://github.com/NickCrews/mismo"

[tool.pdm.dev-dependencies]
lint = ["ruff", "mypy", "pre-commit"]
test = [
  "pytest",
  "pytest-cov",
  "recordlinkage",
]
docs = [
  "mkdocs-git-revision-date-localized-plugin",
  "mkdocs-jupyter",
  "mkdocs-literate-nav",
  "mkdocs-material",
  "mkdocstrings[python]",
]

[tool.coverage.run]
branch = true
parallel = true
omit = ["mismo/__about__.py"]

[tool.coverage.report]
exclude_lines = ["no cov", "if __name__ == .__main__.:", "if TYPE_CHECKING:"]

[tool.ruff]
extend-include = ["*.ipynb"]
select = [
  "E", # pyflakes
  "F", # pyflakes
  "I", # isort
]

[tool.ruff.isort]
# See https://github.com/charliermarsh/ruff#isort
force-sort-within-sections = true
required-imports = ["from __future__ import annotations"]

[tool.mypy]
# https://mypy.readthedocs.io/en/latest/config_file.html#using-a-pyproject-toml-file
python_version = "3.11"
files = ["mismo"]
pretty = true
show_traceback = true
color_output = true
show_column_numbers = true
show_error_codes = true
show_error_context = true

allow_redefinition = false
check_untyped_defs = true
disallow_any_generics = true
disallow_incomplete_defs = true
ignore_missing_imports = true
implicit_reexport = false
no_implicit_optional = true
strict_equality = true
strict_optional = true
warn_no_return = true
warn_redundant_casts = true
warn_return_any = true
warn_unreachable = true
warn_unused_configs = true
warn_unused_ignores = true
