[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "mismo"
description = ''
readme = "README.md"
requires-python = ">=3.8"
license = "LGPL-3.0-or-later"
keywords = []
authors = [
  { name = "Nick Crews", email = "nicholas.b.crews@gmail.com" },
]
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.7",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: Implementation :: CPython",
  "Programming Language :: Python :: Implementation :: PyPy",
]
dependencies = [
  "dedupe",
  "ibis-framework @ git+https://github.com/ibis-project/ibis@63f985521588935ab4b1e66f0015b68b7753cc73#ibis-framework[duckdb]",
  "recordlinkage",
]
dynamic = ["version"]

[project.urls]
Documentation = "https://github.com/unknown/mismo#readme"
Issues = "https://github.com/unknown/mismo/issues"
Source = "https://github.com/unknown/mismo"

[tool.hatch.version]
path = "mismo/__about__.py"

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.sdist]
[tool.hatch.build.targets.wheel]

[tool.hatch.envs.default]
python = "39"
dependencies = [
  "black[jupyter]",
  "ipykernel",
  "mypy",
  "nbqa",
  "pre-commit",
  "pytest",
  "pytest-cov",
  "ruff",
]

[tool.hatch.envs.default.scripts]
lint = [
  "black --check .",
  "ruff .",
  "nbqa ruff .",
  "mypy .",
]
fmt = [
  "black .",
  "ruff --fix .",
  "nbqa ruff --fix .",
]
cov = "pytest --cov-report=term-missing --cov-config=pyproject.toml --cov=mismo --cov=tests"
no-cov = "cov --no-cov"

[[tool.hatch.envs.test.matrix]]
python = ["38", "39", "310", "311"]

[tool.coverage.run]
branch = true
parallel = true
omit = [
  "mismo/__about__.py",
]

[tool.coverage.report]
exclude_lines = [
  "no cov",
  "if __name__ == .__main__.:",
  "if TYPE_CHECKING:",
]

[tool.ruff]
select = [
  "E",  # pyflakes
  "F",  # pyflakes
  "I",  # isort
]

[tool.ruff.isort]
# See https://github.com/charliermarsh/ruff#isort
force-sort-within-sections = true

[tool.mypy]
# https://mypy.readthedocs.io/en/latest/config_file.html#using-a-pyproject-toml-file
python_version = "3.10"
files = ["mismo"]
pretty = true
show_traceback = true
color_output = true
show_column_numbers = true
show_error_codes = true
show_error_context = true

allow_redefinition = false
check_untyped_defs = true
disallow_any_generics = true
disallow_incomplete_defs = true
ignore_missing_imports = true
implicit_reexport = false
no_implicit_optional = true
strict_equality = true
strict_optional = true
warn_no_return = true
warn_redundant_casts = true
warn_return_any = true
warn_unreachable = true
warn_unused_configs = true
warn_unused_ignores = true
